#!/bin/bash
# Diff the terrain CHUNK SET between a wedge boot and a clean boot at the same
# camera (task #24). Cheaper and more exact than a GPU capture pair: no
# transform replication (my replica-based coverage probes were invalid for
# these draws) and no 200MB writes -- just each chunk's identity.
#
#   tools/chunk_ab.sh [max_runs]
#
# Keeps the [CHUNKDUMP] line from the first matching wedge boot and the first
# matching clean boot, then prints what only one of them has.
# ⚠️ Do not edit this file while it is running (bash reads scripts
# incrementally; an in-flight edit kills the run).
set -u
MAX="${1:-8}"
CAM="${CAM_INDICES:-427617}"
VS=C6C4FBF7D18A3E61
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
B="$ROOT/out/build/linux-amd64-relwithdebinfo"
SUM=/tmp/restuff_drive/chunk_ab.txt
: > "$SUM"
exec 9>/tmp/restuff_drive/.drive.lock
flock 9

score() {
  python3 - "$1" <<'PY'
import sys
from PIL import Image
im = Image.open(sys.argv[1]).convert('RGB'); px = im.load()
n = t = 0
for y in range(440, 620, 4):
    for x in range(80, 560, 4):
        r, g, b = px[x, y]; t += 1
        if b > r + 18 and 40 < b < 175 and g > r - 10: n += 1
print(100 * n // max(t, 1))
PY
}

got_w=0; got_c=0
for i in $(seq 1 "$MAX"); do
  TS=$(date '+%Y-%m-%d %H:%M:%S')
  timeout 1200 "$ROOT/tools/replay_drive.sh" /tmp/hole.padlog chk$i \
    "RESTUFF_PAD_REPLAY_DELAY=900 RESTUFF_VSCOUNT=$VS RESTUFF_CHUNKDUMP=$VS" >/dev/null 2>&1
  LINE=$(grep -ah VSCOUNT "$B"/restuff_dbg.log "$B"/restuff_dbg.1.log 2>/dev/null \
         | awk -v ts="$TS" 'substr($0,2,19) >= ts' | tail -1)
  IDX=$(printf '%s' "$LINE" | grep -oE 'indices=[0-9]+' | cut -d= -f2)
  DRW=$(printf '%s' "$LINE" | grep -oE '(^| )draws=[0-9]+' | head -1 | cut -d= -f2)
  CHUNK=$(grep -ah CHUNKDUMP "$B"/restuff_dbg.log "$B"/restuff_dbg.1.log 2>/dev/null \
          | awk -v ts="$TS" 'substr($0,2,19) >= ts' | tail -1)
  F=/tmp/restuff_drive/env_chk$i/W02.png
  S=$([ -f "$F" ] && score "$F" || echo NA)
  KEEP=discarded
  if [ "${IDX:-0}" = "$CAM" ] && [ -n "$CHUNK" ] && [ "$S" != NA ]; then
    if [ "$S" -ge 15 ] && [ "$got_w" = 0 ]; then
      printf '%s\n' "$CHUNK" > /tmp/restuff_drive/chunks_WEDGE.txt; got_w=1; KEEP=kept_WEDGE
    elif [ "$S" -lt 5 ] && [ "$got_c" = 0 ]; then
      printf '%s\n' "$CHUNK" > /tmp/restuff_drive/chunks_CLEAN.txt; got_c=1; KEEP=kept_CLEAN
    fi
  fi
  echo "chk$i cam=${IDX:-none} draws=${DRW:-?} wedge=${S}% $KEEP" >> "$SUM"
  [ "$got_w" = 1 ] && [ "$got_c" = 1 ] && break
done

if [ "$got_w" = 1 ] && [ "$got_c" = 1 ]; then
  python3 - >> "$SUM" <<'PY'
import re
def load(p):
    txt = open(p).read()
    return set(re.findall(r'([0-9A-F]{8}:\d+/cm[0-9A-F])', txt))
w = load('/tmp/restuff_drive/chunks_WEDGE.txt')
c = load('/tmp/restuff_drive/chunks_CLEAN.txt')
print(f"chunks wedge={len(w)} clean={len(c)} shared={len(w & c)}")
print(f"ONLY-IN-CLEAN ({len(c - w)}): {sorted(c - w)[:25]}")
print(f"ONLY-IN-WEDGE ({len(w - c)}): {sorted(w - c)[:25]}")
PY
fi
cat "$SUM"
