#!/usr/bin/env python3
"""Identify WHICH screen a captured boot frame shows, by template match.

WHY v2 EXISTS: classify_boot.py keys on colour, and the game has FOUR different
pale-blue screens -- the legal notice, the auto-save notice, the loading screen,
and the sign-in prompt. They score nearly identically (auto-save blue=67.80 vs
sign-in blue=68.54), so a colour test cannot tell them apart. Every "DIALOG"
count produced with v1 is really a "pale blue screen" count, which is NOT the
sign-in incidence and must not be quoted as one.

This matches each frame against labelled reference frames instead, so SIGNIN is
distinguished from AUTOSAVE/LOADING/LEGAL.

  usage: classify_boot2.py <dir> [prefix]
"""
import os
import sys
from collections import Counter

try:
    from PIL import Image, ImageChops
except ImportError:
    sys.exit("needs pillow: pip install pillow")

# ⚠️ REFERENCES LIVE ON DISK, NOT IN TMPFS.
# They used to be read straight out of /tmp/restuff_drive/<some old run>/. A
# power cut wiped tmpfs and took every reference with it, which silently
# disarmed the one safeguard this script exists to provide (see DIALOG_REFS
# below). References are now kept in the repo under tools/refs/dialogs/ so they
# survive reboots, and are regenerated by tools/regen_refs.sh.
D = "/tmp/restuff_drive"
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "refs", "dialogs")
REFS = {
    "SIGNIN":   f"{R}/SIGNIN.png",            # "sign in with a gamer profile?"
    # ⚠️ STORAGE looks ALMOST IDENTICAL to SIGNIN -- same box, same two-option
    # layout, distinguishable only by its text ("No storage device is currently
    # selected" / Select Another Device / Continue Without Saving). Without this
    # reference every storage dialog scores as SIGNIN (dist ~1.1) and inflates
    # the sign-in count. Caught by EYE, not by the metric.
    "STORAGE":  f"{R}/STORAGE.png",
    # A THIRD near-identical dialog: "The saved game you are trying to load is
    # corrupt / RETRY / Select Another Device / Create New Game / Continue
    # Without Saving". Scored as STORAGE until this reference existed. The game
    # has a whole family of these felt-box prompts -- sign-in, no-storage,
    # corrupt-save, auto-save -- and colour cannot separate any of them.
    "CORRUPT":  f"{R}/CORRUPT.png",
    "AUTOSAVE": f"{R}/AUTOSAVE.png",          # "This game uses an Auto-Save system"
    "LOADING":  f"{R}/LOADING.png",           # controller layout + "Loading"
    "LEGAL":    f"{R}/LEGAL.png",             # (c) 2010 Artificial Mind and Movement
    "MENU":     f"{R}/MENU.png",              # red main-menu panel
    "GAMEPLAY": f"{R}/GAMEPLAY.png",          # hut door
}
# Any SIGNIN count produced without these present is NOT a sign-in count: the
# storage and corrupt-save prompts are the same felt box with different text and
# land ~1.1 away from SIGNIN, i.e. they win outright when SIGNIN is the only
# dialog reference loaded. That is how a storage-dialog batch was once reported
# as sign-in hits. Missing either one is a hard error, never a silent fallback.
DIALOG_REFS = ("SIGNIN", "STORAGE", "CORRUPT")
SIZE = (80, 45)


def sig(path):
    im = Image.open(path).convert("RGB").resize(SIZE)
    return im


def dist(a, b):
    diff = ImageChops.difference(a, b)
    h = diff.convert("L").histogram()
    total = sum(i * n for i, n in enumerate(h))
    return total / float(SIZE[0] * SIZE[1])


def main():
    refs = {}
    for name, p in REFS.items():
        if os.path.exists(p):
            refs[name] = sig(p)
    missing = [k for k in DIALOG_REFS if k not in refs]
    if missing:
        sys.exit("missing dialog reference(s) %s in %s -- a SIGNIN count without "
                 "them counts storage/corrupt prompts as sign-ins. Run "
                 "tools/regen_refs.sh." % (",".join(missing), R))
    root = sys.argv[1] if len(sys.argv) > 1 else D
    prefix = sys.argv[2] if len(sys.argv) > 2 else "env_"
    counts = Counter()
    for name in sorted(os.listdir(root)):
        if not name.startswith(prefix):
            continue
        frame = os.path.join(root, name, "W01.png")
        if not os.path.exists(frame):
            continue
        s = sig(frame)
        best, bestd = min(((k, dist(s, v)) for k, v in refs.items()), key=lambda kv: kv[1])
        counts[best] += 1
        if best == "SIGNIN":
            print("%-24s %-9s dist=%.1f" % (name, best, bestd))
    print("\n" + " ".join("%s=%d" % (k, v) for k, v in sorted(counts.items())))


if __name__ == "__main__":
    main()
