#!/bin/bash
# Sector-table SIGNATURE under the EMULATED renderer (task #24).
#
#   tools/emu_signature.sh <tag> [runs]
#
# ⚠️ BLOCKED — DO NOT USE AS WRITTEN. It reads the family from the sector-table
# signature, and mk1 refuted that premise (a MERGED boot scored 1/1/1/1 while a
# WEDGE boot scored 6/6/5/5). The emulated 3D path renders nothing here, so a
# frame score is also unavailable — which leaves this arm with no trustworthy
# outcome measure at all. Kept only as the harness skeleton; it needs a VALIDATED
# early classifier (tested on both families, n>1 each) before it can answer
# anything.
#
# THE QUESTION: the defect is frozen during LOAD, and the recorded trigger is
# CPU contention in that window (a cold driver pipeline cache induces it
# reliably-ish). Our native renderer compiles shaders during load; the SDK
# emulated path does not do that work. If emulated boots land high signatures
# while native boots scatter low, our load-window cost is implicated and the
# fix is ours to make (task #20, persist translated SPIR-V). If both scatter
# the same way, our renderer is exonerated and the cause is in the guest's own
# load path.
#
# Runs are cut short deliberately: the signature is readable at ~90s, long
# before the door, so there is no reason to drive the whole route.
# ⚠️ Do not edit this file while it runs (bash reads scripts incrementally).
set -u
TAG="${1:?usage: emu_signature.sh <tag> [runs]}"
RUNS="${2:-4}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="/tmp/restuff_drive/emusig_$TAG"
mkdir -p /tmp/restuff_drive
exec 9>/tmp/restuff_drive/.drive.lock
if ! flock -w 120 9; then
  echo "ABORT: drive lock busy >120s"; exit 3
fi
# replay_emulated REFUSES to start if any game is alive; we hold the lock, so
# anything running now is a stray by definition (this exact leftover made an
# entire earlier emulated arm report 6/6 NA).
pkill -9 -x restuff 2>/dev/null; pkill -x Xvfb 2>/dev/null
sleep 2; rm -f /dev/shm/xenia_memory_* 2>/dev/null

for i in $(seq 1 "$RUNS"); do
  L="/tmp/restuff_drive/mergelog.txt"
  mv -f "$L" "/tmp/restuff_drive/mergelog_pre_${TAG}$i.txt" 2>/dev/null
  echo "[emu_signature] ${TAG}$i starting $(date '+%H:%M:%S')"
  timeout 420 "$ROOT/tools/replay_emulated.sh" /tmp/hole.padlog "${TAG}$i" \
    "RESTUFF_PAD_REPLAY_DELAY=900 RESTUFF_MERGELOG=1 RESTUFF_IBWATCH=13F00000,13F01000" \
    >/dev/null 2>&1
  pkill -9 -x restuff 2>/dev/null; pkill -x Xvfb 2>/dev/null; sleep 2
  cp -f "$L" "${OUT}_$i.txt" 2>/dev/null
  python3 "$ROOT/tools/sector_signature.py" "${OUT}_$i.txt" 2>&1 | sed 's/^/    /'
done
echo "[emu_signature] done; logs at ${OUT}_*.txt"
