#!/bin/bash
# Wedge test under the EMULATED renderer (task #24).
#
#   tools/emu_ab.sh <tag> [runs]
#
# THE decisive extent experiment: the SDK CommandProcessor computes REAL
# screen extents (M3.36 note — the emulated path never starved visibility),
# while our native walker fabricates a constant. Same guest, same route, same
# scorer. If the wedge NEVER appears here (native: ~75% of matched boots) the
# fabricated-extent theory is confirmed; if it appears anyway, extents are
# exonerated for the partition choice.
#
# ⚠️ No VSCOUNT under emulation (native-side instrument), so there is no
# camera fingerprint: eyeball every W02.png. Recent native drift was 0/8, and
# the score region only reads the lower-left ground.
# ⚠️ Do not edit this file while it runs (bash reads scripts incrementally).
set -u
TAG="${1:?usage: emu_ab.sh <tag> [runs]}"
RUNS="${2:-6}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUM="/tmp/restuff_drive/wedge_ab_$TAG.txt"
mkdir -p /tmp/restuff_drive
: > "$SUM"
exec 9>/tmp/restuff_drive/.drive.lock
flock 9
# replay_drive leaves the LAST run's game alive (the next replay_drive clears
# strays) -- but replay_emulated REFUSES to start when pgrep sees any game, so
# a leftover from the previous arm made every emulated run refuse instantly
# (6/6 NA, refusal swallowed by the output redirect). We hold the drive lock,
# so any game now alive is a stray by definition: clear it ourselves.
pkill -9 -x restuff 2>/dev/null; pkill -x Xvfb 2>/dev/null
sleep 2; rm -f /dev/shm/xenia_memory_* 2>/dev/null

score() {
  python3 - "$1" <<'PY'
import sys
from PIL import Image
im = Image.open(sys.argv[1]).convert('RGB'); px = im.load()
n = t = 0
for y in range(440, 620, 4):
    for x in range(80, 560, 4):
        r, g, b = px[x, y]; t += 1
        if b > r + 18 and 40 < b < 175 and g > r - 10: n += 1
print(round(100 * n / max(t, 1)))
PY
}

for i in $(seq 1 "$RUNS"); do
  timeout 1500 "$ROOT/tools/replay_emulated.sh" /tmp/hole.padlog "${TAG}$i" \
    "RESTUFF_PAD_REPLAY_DELAY=900" >/dev/null 2>&1
  D="/tmp/restuff_drive/env_${TAG}$i"
  F="$D/W02.png"
  if [ -f "$F" ]; then
    S=$(score "$F")
    cp -f "$F" "/tmp/restuff_drive/emu_${TAG}${i}_W02.png"  # keep for eyeball
  elif grep -qaE "corrupted|Segmentation|X connection to :99 broken" "$D/run.log" 2>/dev/null; then
    S=CRASH
  else
    S=NA
  fi
  echo "${TAG}$i wedge=${S}% (emulated; eyeball emu_${TAG}${i}_W02.png)" >> "$SUM"
done
echo "done runs=$RUNS" >> "$SUM"
