#!/bin/bash
# Fast wedge/clean classification WITHOUT the route (task #24).
#
#   tools/fast_classify.sh <tag> <runs> [ENV=VAL ...]
#
# The wedge outcome is decided in early gameplay: cm0 chunk total at dump 2+
# separates 6/6 (212562=wedge family, 212913=clean) while dump 1 (306266) is
# still uniform. So a boot only needs to reach early gameplay and emit a few
# dumps (~4-5 min with menus) — no route, no camera matching. ~2-3x the
# throughput of wedge_ab for outcome-RATE experiments.
#
# Uses the normal padlog (menus need input) but kills the game once enough
# dumps landed. Trajectory (all dump totals) is recorded per run — the
# bifurcation BAND matters as much as the verdict.
# ⚠️ Do not edit this file while it runs (bash reads scripts incrementally).
set -u
TAG="${1:?usage: fast_classify.sh <tag> <runs> [ENV=VAL ...]}"
RUNS="${2:?need run count}"; shift 2 || true
ENVKV="${*:-}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
B="$ROOT/out/build/linux-amd64-relwithdebinfo"
SUM="/tmp/restuff_drive/fastcls_$TAG.txt"
mkdir -p /tmp/restuff_drive; : > "$SUM"
exec 9>/tmp/restuff_drive/.drive.lock
flock 9

NEED_DUMPS="${NEED_DUMPS:-10}"
for i in $(seq 1 "$RUNS"); do
  pkill -9 -x restuff 2>/dev/null; pkill -x Xvfb 2>/dev/null; sleep 1
  rm -f /dev/shm/xenia_memory_* 2>/dev/null
  Xvfb :99 -screen 0 1280x720x24 >/dev/null 2>&1 & sleep 2
  TS=$(date '+%Y-%m-%d %H:%M:%S')
  D="/tmp/restuff_drive/env_fc_${TAG}$i"; mkdir -p "$D"
  # STRESS=N,DUR: run N busy-loop cores for DUR seconds alongside the boot
  # (perturbs thread scheduling during the family-decision window).
  if [ -n "${STRESS:-}" ]; then
    bash /tmp/restuff_drive/stress_wrap.sh "${STRESS%,*}" "${STRESS#*,}" &
    STRESSPID=$!
  fi
  ( cd "$B" && env $ENVKV RESTUFF_CHUNKDUMP=C6C4FBF7D18A3E61 RESTUFF_CHUNKDUMP_EVERY=40 \
      RESTUFF_PAD_REPLAY=/tmp/hole.padlog RESTUFF_PAD_REPLAY_DELAY=900 \
      DISPLAY=:99 SDL_VIDEODRIVER=x11 ./restuff > "$D/run.log" 2>&1 ) &
  GAME=$!
  # wait for NEED_DUMPS dumps (or 420s hard cap)
  for _ in $(seq 1 210); do
    sleep 2
    N=$(grep -ah "CHUNKDUMP" "$B"/restuff_dbg.log "$B"/restuff_dbg.1.log 2>/dev/null \
        | awk -v ts="$TS" 'substr($0,2,19) >= ts' | wc -l)
    [ "$N" -ge "$NEED_DUMPS" ] && break
    kill -0 $GAME 2>/dev/null || break
  done
  grep -ah "CHUNKDUMP" "$B"/restuff_dbg.log "$B"/restuff_dbg.1.log 2>/dev/null \
    | awk -v ts="$TS" 'substr($0,2,19) >= ts' > "$D/dumps.log"
  kill -9 $GAME 2>/dev/null; pkill -9 -x restuff 2>/dev/null; pkill -x Xvfb 2>/dev/null
  [ -n "${STRESS:-}" ] && { kill $STRESSPID 2>/dev/null; pkill -f stress_wrap 2>/dev/null || true; }
  python3 - "$D/dumps.log" >> "$SUM" <<PY
import sys, re
tag = "${TAG}$i"
totals = []
for l in open(sys.argv[1]):
    counts = [int(m) for m in re.findall(r'[0-9A-F]{8}:(\d+)/cm0 ', l)]
    if counts: totals.append(sum(counts))
# Totals are VIEW-DEPENDENT (cutscene pan values 306266/323194/351417/22xxxx
# wander); the FAMILY shows in the steady tail (and usually already at dump 1,
# the spawn view). Known families at the spawn/walk views:
#   A = 212562  wedge (~30%% score at the door)
#   B = 212913  clean
#   C = 209677  near-clean (finer partition; 4%% family)
FAM = {212562: "A_WEDGE", 212913: "B_CLEAN", 209677: "C_FINE"}
verdict = "NA"
tail = totals[-3:]
if len(tail) == 3 and len(set(tail)) == 1 and tail[0] in FAM:
    verdict = FAM[tail[0]]
elif totals and totals[0] in FAM:
    verdict = FAM[totals[0]] + "?"
elif tail:
    verdict = f"OTHER({tail[-1]})"
print(f"{tag} dumps={len(totals)} traj={totals[:8]} verdict={verdict}")
PY
done
cat "$SUM"
