#!/bin/bash
# Camera-matched A/B over engine.ini variants (task #24).
#
#   tools/ini_ab.sh <tag> <ini-file> [runs]
#
# Swaps assets/engine.ini for the given variant, runs the camera-matched
# wedge harness, and ALWAYS restores the original (trap) -- a previous inline
# attempt at this class of thing left a modified config behind when killed.
#
# Motive: the earlier graphics-batching test was scored by DRAW COUNT on
# camera-unmatched runs, which is exactly the confound that invalidated two
# other conclusions. Any ini claim has to come through wedge_ab.sh.
# ⚠️ Do not edit this file while it runs (bash reads scripts incrementally).
set -u
TAG="${1:?usage: ini_ab.sh <tag> <ini-file> [runs]}"
INI="${2:?need an ini file}"
RUNS="${3:-5}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Take the drive lock BEFORE touching engine.ini. wedge_ab.sh locks internally,
# but the config is GLOBAL STATE: swapping it while another arm is mid-flight
# silently changes that arm's configuration (it did -- an extent-semantics arm
# ran with a batching variant underneath it, confounding both).
exec 8>/tmp/restuff_drive/.drive.lock
flock 8
BAK=/tmp/restuff_drive/engine_ini_$TAG.bak
cp "$ROOT/assets/engine.ini" "$BAK" 2>/dev/null || : > "$BAK"
restore() { cp -f "$BAK" "$ROOT/assets/engine.ini"; echo "[ini_ab] engine.ini restored"; }
trap restore EXIT INT TERM
cp -f "$INI" "$ROOT/assets/engine.ini"
echo "[ini_ab] using:"; sed 's/^/    /' "$ROOT/assets/engine.ini"
# Release before wedge_ab.sh (it takes the same lock on its own fd) but keep
# the ini in place for the whole arm; the trap restores it either way.
flock -u 8
RUNS="$RUNS" "$ROOT/tools/wedge_ab.sh" "$TAG"
